"""add email

Revision ID: 041654c7e86e
Revises: 
Create Date: 2024-01-14 11:50:20.829224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041654c7e86e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
